server {
    listen 80;

    # Handling root requests (React application)
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri /index.html;
    }

    # Static files (like CSS/JS/fonts)
    location /static/ {
        root /usr/share/nginx/html;
        expires max;
        access_log off;
    }
}
